
import 'dart:ui';

import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../../foo_form_field.dart';

extension TextFormFieldPropertiesExtension<T> on TextFormFieldProperties<T>? {
  
  TextFormFieldProperties<T> merge({
    required TextFormFieldProperties<T>? secondary,
  }) {

    if (this == null) {
      return secondary ?? TextFormFieldProperties<T>();
    }

    return TextFormFieldProperties(
      decoration: this?.decoration.merge(
        secondary: secondary?.decoration,
      ),
      autocorrect: this?.autocorrect ?? secondary?.autocorrect,
      autofillHints: this?.autofillHints ?? secondary?.autofillHints,
      autovalidateMode: this?.autovalidateMode ?? secondary?.autovalidateMode,
      buildCounter: this?.buildCounter ?? secondary?.buildCounter,
      cursorColor: this?.cursorColor ?? secondary?.cursorColor,
      cursorHeight: this?.cursorHeight ?? secondary?.cursorHeight,
      cursorOpacityAnimates:this?.cursorOpacityAnimates ?? secondary?.cursorOpacityAnimates,
      showCursor: this?.showCursor ?? secondary?.showCursor,
      textInputAction: this?.textInputAction ?? secondary?.textInputAction,
      textCapitalization: this?.textCapitalization ?? secondary?.textCapitalization,
      textDirection: this?.textDirection ?? secondary?.textDirection,
      textAlign: this?.textAlign ?? secondary?.textAlign,
      textAlignVertical: this?.textAlignVertical ?? secondary?.textAlignVertical,
      enableInteractiveSelection: this?.enableInteractiveSelection ?? secondary?.enableInteractiveSelection,
      enableSuggestions: this?.enableSuggestions ?? secondary?.enableSuggestions,
      enableIMEPersonalizedLearning: this?.enableIMEPersonalizedLearning ?? secondary?.enableIMEPersonalizedLearning,
      autofocus: this?.autofocus ?? secondary?.autofocus,
      obscureText: this?.obscureText ?? secondary?.obscureText,
      obscuringCharacter: this?.obscuringCharacter ?? secondary?.obscuringCharacter,
      readOnly: this?.readOnly ?? secondary?.readOnly,
      maxLength: this?.maxLength ?? secondary?.maxLength,
      maxLines: this?.maxLines ?? secondary?.maxLines,
      minLines: this?.minLines ?? secondary?.minLines,
      onTap: this?.onTap ?? secondary?.onTap,
      onFieldSubmitted: this?.onFieldSubmitted ?? secondary?.onFieldSubmitted,
      onTapOutside: this?.onTapOutside ?? secondary?.onTapOutside,
      onChanged: this?.onChanged ?? secondary?.onChanged,
      onEditingComplete: this?.onEditingComplete ?? secondary?.onEditingComplete,
      onSaved: this?.onSaved ?? secondary?.onSaved,
      canRequestFocus: this?.canRequestFocus ?? secondary?.canRequestFocus,
      clipBehavior: this?.clipBehavior ?? secondary?.clipBehavior,
      style: this?.style ?? secondary?.style,
      contentInsertionConfiguration:this?.contentInsertionConfiguration ?? secondary?.contentInsertionConfiguration,
      cursorErrorColor: this?.cursorErrorColor ?? secondary?.cursorErrorColor,
      cursorRadius: this?.cursorRadius ?? secondary?.cursorRadius,
      cursorWidth: this?.cursorWidth ?? secondary?.cursorWidth,
      dragStartBehavior: this?.dragStartBehavior ?? secondary?.dragStartBehavior,
      expands: this?.expands ?? secondary?.expands,
      inputFormatters: this?.inputFormatters ?? secondary?.inputFormatters,
      maxLengthEnforcement: this?.maxLengthEnforcement ?? secondary?.maxLengthEnforcement,
      mouseCursor: this?.mouseCursor ?? secondary?.mouseCursor,
      scrollPadding: this?.scrollPadding ?? secondary?.scrollPadding,
      scrollPhysics: this?.scrollPhysics ?? secondary?.scrollPhysics,
      errorBuilder: this?.errorBuilder ?? secondary?.errorBuilder,
      focusNode: this?.focusNode ?? secondary?.focusNode,
      ignorePointers: this?.ignorePointers ?? secondary?.ignorePointers,
      restorationId: this?.restorationId ?? secondary?.restorationId,
      selectionControls: this?.selectionControls ?? secondary?.selectionControls,
      selectionHeightStyle: this?.selectionHeightStyle ?? secondary?.selectionHeightStyle,
      selectionWidthStyle: this?.selectionWidthStyle ?? secondary?.selectionWidthStyle,
      keyboardAppearance: this?.keyboardAppearance ?? secondary?.keyboardAppearance,
      magnifierConfiguration: this?.magnifierConfiguration ?? secondary?.magnifierConfiguration,
      scrollController: this?.scrollController ?? secondary?.scrollController,
      onAppPrivateCommand: this?.onAppPrivateCommand ?? secondary?.onAppPrivateCommand,
      undoController: this?.undoController ?? secondary?.undoController,
      onTapUpOutside: this?.onTapUpOutside ?? secondary?.onTapUpOutside,
      smartDashesType: this?.smartDashesType ?? secondary?.smartDashesType,
      onTapAlwaysCalled: this?.onTapAlwaysCalled ?? secondary?.onTapAlwaysCalled,
      spellCheckConfiguration:this?.spellCheckConfiguration ?? secondary?.spellCheckConfiguration,
      smartQuotesType: this?.smartQuotesType ?? secondary?.smartQuotesType,
      strutStyle: this?.strutStyle ?? secondary?.strutStyle,
      stylusHandwritingEnabled:this?.stylusHandwritingEnabled ?? secondary?.stylusHandwritingEnabled,
      validator: this?.validator ?? secondary?.validator,
      groupId: this?.groupId ?? secondary?.groupId ?? Object(),
    );
  }

  TextFormFieldProperties<T> mergeDecoration({
    required InputDecoration? secondaryDecoration,
  }) {
    return merge(
      secondary: TextFormFieldProperties<T>(
        decoration: secondaryDecoration,
      ),
    );
  }

  TextFormFieldProperties<T> addRequiredValidator({
    required String message,
  }){
    return copyWith(
      validator: (value) {
        if (value == null || value.toString().trim().isEmpty) {
          return message;
        }
        return this?.validator?.call(value);
      },
    );
  }

  TextFormFieldProperties<T> copyWith({
    InputDecoration? decoration,
    List<TextInputFormatter>? inputFormatters,
    Object? groupId,
    FocusNode? focusNode,
    TextCapitalization? textCapitalization,
    TextInputAction? textInputAction,
    TextStyle? style,
    StrutStyle? strutStyle,
    TextDirection? textDirection,
    TextAlign? textAlign,
    TextAlignVertical? textAlignVertical,
    bool? autofocus,
    bool? readOnly,
    bool? showCursor,
    String? obscuringCharacter,
    bool? obscureText,
    bool? autocorrect,
    SmartDashesType? smartDashesType,
    SmartQuotesType? smartQuotesType,
    bool? enableSuggestions,
    MaxLengthEnforcement? maxLengthEnforcement,
    int? maxLines,
    int? minLines,
    bool? expands,
    int? maxLength,
    void Function(T? value)? onChanged,
    GestureTapCallback? onTap,
    bool? onTapAlwaysCalled,
    TapRegionCallback? onTapOutside,
    TapRegionUpCallback? onTapUpOutside,
    VoidCallback? onEditingComplete,
    ValueChanged<T?>? onFieldSubmitted,
    void Function(T? value)? onSaved,
    String? Function(T? value)? validator,
    FormFieldErrorBuilder? errorBuilder,
    bool? ignorePointers,
    double? cursorWidth,
    double? cursorHeight,
    Radius? cursorRadius,
    Color? cursorColor,
    Color? cursorErrorColor,
    Brightness? keyboardAppearance,
    EdgeInsets? scrollPadding,
    bool? enableInteractiveSelection,
    TextSelectionControls? selectionControls,
    InputCounterWidgetBuilder? buildCounter,
    ScrollPhysics? scrollPhysics,
    Iterable<String>? autofillHints,
    AutovalidateMode? autovalidateMode,
    ScrollController? scrollController,
    String? restorationId,
    bool? enableIMEPersonalizedLearning,
    MouseCursor? mouseCursor,
    SpellCheckConfiguration? spellCheckConfiguration,
    TextMagnifierConfiguration? magnifierConfiguration,
    UndoHistoryController? undoController,
    AppPrivateCommandCallback? onAppPrivateCommand, 
    bool? cursorOpacityAnimates,
    BoxHeightStyle? selectionHeightStyle,
    BoxWidthStyle? selectionWidthStyle,
    DragStartBehavior? dragStartBehavior,
    ContentInsertionConfiguration? contentInsertionConfiguration,
    Clip? clipBehavior,
    bool? stylusHandwritingEnabled,
    bool? canRequestFocus,
    String? forceErrorText,
  }){
    return TextFormFieldProperties(
      decoration: decoration ?? this?.decoration,
      autocorrect: autocorrect ?? this?.autocorrect,
      autofillHints: autofillHints ?? this?.autofillHints,
      autovalidateMode: autovalidateMode ?? this?.autovalidateMode,
      buildCounter: buildCounter ?? this?.buildCounter,
      cursorColor: cursorColor ?? this?.cursorColor,
      cursorHeight: cursorHeight ?? this?.cursorHeight,
      cursorOpacityAnimates:cursorOpacityAnimates ?? this?.cursorOpacityAnimates,
      showCursor: showCursor ?? this?.showCursor,
      textInputAction: textInputAction ?? this?.textInputAction,
      textCapitalization: textCapitalization ?? this?.textCapitalization,
      textDirection: textDirection ?? this?.textDirection,
      textAlign: textAlign ?? this?.textAlign,
      textAlignVertical: textAlignVertical ?? this?.textAlignVertical,
      enableInteractiveSelection: enableInteractiveSelection ?? this?.enableInteractiveSelection,
      enableSuggestions: enableSuggestions ?? this?.enableSuggestions,
      enableIMEPersonalizedLearning: enableIMEPersonalizedLearning ?? this?.enableIMEPersonalizedLearning,
      autofocus: autofocus ?? this?.autofocus,
      obscureText: obscureText ?? this?.obscureText,
      obscuringCharacter: obscuringCharacter ?? this?.obscuringCharacter,
      readOnly: readOnly ?? this?.readOnly,
      maxLength: maxLength ?? this?.maxLength,
      maxLines: maxLines ?? this?.maxLines,
      minLines: minLines ?? this?.minLines,
      onTap: onTap ?? this?.onTap,
      onFieldSubmitted: onFieldSubmitted ?? this?.onFieldSubmitted,
      onTapOutside: onTapOutside ?? this?.onTapOutside,
      onChanged: onChanged ?? this?.onChanged,
      onEditingComplete: onEditingComplete ?? this?.onEditingComplete,
      onSaved: onSaved ?? this?.onSaved,
      canRequestFocus: canRequestFocus ?? this?.canRequestFocus,
      clipBehavior: clipBehavior ?? this?.clipBehavior,
      style: style ?? this?.style,
      contentInsertionConfiguration:contentInsertionConfiguration ?? this?.contentInsertionConfiguration,
      cursorErrorColor: cursorErrorColor ?? this?.cursorErrorColor,
      cursorRadius: cursorRadius ?? this?.cursorRadius,
      cursorWidth: cursorWidth ?? this?.cursorWidth,
      dragStartBehavior: dragStartBehavior ?? this?.dragStartBehavior,
      expands: expands ?? this?.expands,
      inputFormatters: inputFormatters ?? this?.inputFormatters,
      maxLengthEnforcement: maxLengthEnforcement ?? this?.maxLengthEnforcement,
      mouseCursor: mouseCursor ?? this?.mouseCursor,
      scrollPadding: scrollPadding ?? this?.scrollPadding,
      scrollPhysics: scrollPhysics ?? this?.scrollPhysics,
      errorBuilder: errorBuilder ?? this?.errorBuilder,
      focusNode: focusNode ?? this?.focusNode,
      ignorePointers: ignorePointers ?? this?.ignorePointers,
      restorationId: restorationId ?? this?.restorationId,
      selectionControls: selectionControls ?? this?.selectionControls,
      selectionHeightStyle: selectionHeightStyle ?? this?.selectionHeightStyle,
      selectionWidthStyle: selectionWidthStyle ?? this?.selectionWidthStyle,
      keyboardAppearance: keyboardAppearance ?? this?.keyboardAppearance,
      magnifierConfiguration: magnifierConfiguration ?? this?.magnifierConfiguration,
      scrollController: scrollController ?? this?.scrollController,
      onAppPrivateCommand: onAppPrivateCommand ?? this?.onAppPrivateCommand,
      undoController: undoController ?? this?.undoController,
      onTapUpOutside: onTapUpOutside ?? this?.onTapUpOutside,
      smartDashesType: smartDashesType ?? this?.smartDashesType,
      onTapAlwaysCalled: onTapAlwaysCalled ?? this?.onTapAlwaysCalled,
      spellCheckConfiguration:spellCheckConfiguration ?? this?.spellCheckConfiguration,
      smartQuotesType: smartQuotesType ?? this?.smartQuotesType,
      strutStyle: strutStyle ?? this?.strutStyle,
      stylusHandwritingEnabled:stylusHandwritingEnabled ?? this?.stylusHandwritingEnabled,
      validator: validator ?? this?.validator,
      groupId: groupId ?? this?.groupId ?? Object(),
      forceErrorText: forceErrorText ?? this?.forceErrorText,
    );
  }
}
